version: 2.1


orbs:
  node: circleci/node@1.1.6
  browser-tools: circleci/browser-tools@1.0.1
  aws-ecr: circleci/aws-ecr@6.11.0
  aws-ecs: circleci/aws-ecs@1.2.0
  slack: circleci/slack@3.4.2

jobs:

  long-second-stage:
    docker:
      - image: circleci/node:14.6.0-browsers
    resource_class: small
    steps:
      - run: echo "Test"


workflows:

#  "Acceptance test (long running)":
#    triggers:
#      - schedule:
          # To avoid eating all credits set current day number (1: Monday, 4: Thursday, etc.)
          # At minute 0 past hour 8, 10, 12, 14, 16, and 18 on Thursday.
#          cron: "0 8,10,12,14,16,18 * * 4"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - long-second-stage
